### PR TITLE
feat: add community module for permify service

### PR DESCRIPTION
**Pull request by theoriginalstove**
Wanted to create a community module for Permify since I also wanted to use testcontainers within my own go code and saw this issue on the Permify repo: https://github.com/Permify/permify/issues/1304

### CODE REVIEW

**Review by mdelapenya — COMMENTED** [review]
Could you update the module's README? It still uses RunContainer in the code snippets https://github.com/theoriginalstove/testcontainers-permify/blob/main/README.md?plain=1#L39

Thanks!

**Comment by theoriginalstove** [comment]
@mdelapenya of course! Didn't realize I forgot to update the examples in the README. Thanks for pointing that out 😅

**Review by kiview — APPROVED** [review]

**Comment by kiview** [comment]
Thanks for adding this and working on the module @theoriginalstove 🙌

**Comment by theoriginalstove** [comment]
No problem! There was plenty of examples and docs to make it easy and quick to create it. I think I spent 3x the hours trying figure out why the tests failed in the Github action vs passing locally 😅

**Pull request merged**
